export const ADD_TO_DO_SUCCESS = '할일 추가가 성공했습니다.';
export const DELETE_TO_DO_CONFIRMATION = '할일을 삭제하시겠어요?';
export const DELETE_TO_DO_SUCCESS = '할일 삭제가 성공했습니다.';
export const LOGIN_SUCCESS = '로그인에 성공했습니다.';
export const LOGOUT_CONFIRMATION = '로그아웃 하시겠습니까?';
export const LOGOUT_SUCCESS = '현재 계정은 로그아웃되었습니다.';
export const PLEASE_LOGIN = '로그인 후 다시 시도해주세요.';
export const SIGN_UP_SUCCESS = '회원가입에 성공했습니다.';
export const UPDATE_TO_DO_SUCCESS = '할일 수정이 성공했습니다.';
